# Generated by Django 4.1.2 on 2022-11-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_image_link', models.URLField()),
                ('blog_link', models.URLField()),
                ('brief_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
