# Generated by Django 4.1.2 on 2022-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_eductation_school_experience_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eductation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eductation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='eductation',
            name='duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
