# Generated by Django 4.1.2 on 2022-11-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
